/**
 * Generated by tools/stamp-version.js — do not edit by hand.
 * Run `npm run stamp` after bumping the version in package.json.
 */
export const VERSION = '1.10.0';
export const BUILT = '2026-08-30';
export const REPO = 'markbus7/pokertrainer';

/** Where the update check looks: the same package.json on the main branch. */
export const MANIFEST_URL = `https://raw.githubusercontent.com/${REPO}/main/package.json`;

/** Compare two semver strings. Returns -1, 0 or 1. */
export function compareVersions(a, b) {
  const pa = String(a).split('.').map(Number);
  const pb = String(b).split('.').map(Number);
  for (let i = 0; i < 3; i++) {
    const x = pa[i] || 0;
    const y = pb[i] || 0;
    if (x !== y) return x < y ? -1 : 1;
  }
  return 0;
}

/**
 * Ask GitHub what the current released version is.
 * Never throws — a failed check reports itself rather than breaking the page.
 */
export async function checkForUpdate() {
  try {
    const res = await fetch(MANIFEST_URL, { cache: 'no-store' });
    if (!res.ok) return { ok: false, reason: 'http', message: `GitHub returned ${res.status}.` };
    const remote = await res.json();
    if (!remote || typeof remote.version !== 'string') {
      return { ok: false, reason: 'malformed', message: 'Could not read the published version.' };
    }
    const cmp = compareVersions(VERSION, remote.version);
    return { ok: true, current: VERSION, latest: remote.version, upToDate: cmp >= 0, behind: cmp < 0 };
  } catch {
    return { ok: false, reason: 'network', message: 'Could not reach GitHub — check your connection.' };
  }
}
