/**
 * Writes src/js/version.js from package.json, so the running app can state
 * which build it is. Run before shipping: `npm run stamp`.
 *
 * package.json is the single source of truth for the version number — the
 * in-app update check compares against that same file on the main branch,
 * which avoids the chicken-and-egg of trying to stamp a commit's own hash.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));
const built = new Date().toISOString().slice(0, 10);

writeFileSync(
  new URL('../src/js/version.js', import.meta.url),
  `/**
 * Generated by tools/stamp-version.js — do not edit by hand.
 * Run \`npm run stamp\` after bumping the version in package.json.
 */
export const VERSION = '${pkg.version}';
export const BUILT = '${built}';
export const REPO = 'markbus7/pokertrainer';

/** Where the update check looks: the same package.json on the main branch. */
export const MANIFEST_URL = \`https://raw.githubusercontent.com/\${REPO}/main/package.json\`;

/** Compare two semver strings. Returns -1, 0 or 1. */
export function compareVersions(a, b) {
  const pa = String(a).split('.').map(Number);
  const pb = String(b).split('.').map(Number);
  for (let i = 0; i < 3; i++) {
    const x = pa[i] || 0;
    const y = pb[i] || 0;
    if (x !== y) return x < y ? -1 : 1;
  }
  return 0;
}

/**
 * Ask GitHub what the current released version is.
 * Never throws — a failed check reports itself rather than breaking the page.
 */
export async function checkForUpdate() {
  try {
    const res = await fetch(MANIFEST_URL, { cache: 'no-store' });
    if (!res.ok) return { ok: false, reason: 'http', message: \`GitHub returned \${res.status}.\` };
    const remote = await res.json();
    if (!remote || typeof remote.version !== 'string') {
      return { ok: false, reason: 'malformed', message: 'Could not read the published version.' };
    }
    const cmp = compareVersions(VERSION, remote.version);
    return { ok: true, current: VERSION, latest: remote.version, upToDate: cmp >= 0, behind: cmp < 0 };
  } catch {
    return { ok: false, reason: 'network', message: 'Could not reach GitHub — check your connection.' };
  }
}
`,
);

console.log(`Stamped v${pkg.version} (built ${built})`);
